
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu May 08 12:59:30 CEST 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 41;
  public static final int LBRACKET = 33;
  public static final int INCREMENT = 29;
  public static final int CONST = 14;
  public static final int CHAR = 19;
  public static final int EQUALS = 48;
  public static final int CONTINUE = 35;
  public static final int LPAREN = 6;
  public static final int GREATER = 23;
  public static final int SEMI = 5;
  public static final int INTERFACE = 40;
  public static final int MINUS = 46;
  public static final int LESS = 25;
  public static final int DECREMENT = 30;
  public static final int RPAREN = 7;
  public static final int AND = 27;
  public static final int OR = 28;
  public static final int BOOL = 18;
  public static final int COMMA = 8;
  public static final int CLASS = 37;
  public static final int DIV = 47;
  public static final int PLUS = 11;
  public static final int ASSIGN = 15;
  public static final int GREATER_EQUALS = 24;
  public static final int IF = 20;
  public static final int DOT = 32;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RBRACKET = 34;
  public static final int EQUAL = 12;
  public static final int NEW = 42;
  public static final int error = 1;
  public static final int MUL = 50;
  public static final int MOD = 49;
  public static final int NUMBER = 16;
  public static final int BREAK = 36;
  public static final int IDENT = 17;
  public static final int VOID = 13;
  public static final int COLON = 31;
  public static final int UNION = 44;
  public static final int LBRACE = 3;
  public static final int ELSE = 21;
  public static final int LESS_EQUALS = 26;
  public static final int READ = 43;
  public static final int WHILE = 45;
  public static final int NOT_EQUALS = 22;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 39;
  public static final int PROG = 2;
  public static final int DO = 38;
  public static final int PRINT = 9;
}

